name: Build & Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            525515400715.dkr.ecr.eu-west-3.amazonaws.com/starkware-dev-app
            933520531266.dkr.ecr.eu-west-3.amazonaws.com/starkware-prod-app
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr
            type=raw,value={{branch}}-{{sha}},enable={{is_default_branch}}
            type=ref,event=tag

      - name: Configure AWS Credentials - DEV Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::525515400715:role/ecr-push-starkware-dev-starkware
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR - DEV Account
        uses: docker/login-action@v2
        with:
          registry: 525515400715.dkr.ecr.eu-west-3.amazonaws.com

      - name: Configure AWS Credentials - Production Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
         role-to-assume: arn:aws:iam::933520531266:role/ecr-push-starkware-prod-starkware
         aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR - Production Account
        uses: docker/login-action@v2
        with:
         registry: 297886154276.dkr.ecr.eu-west-3.amazonaws.com

      - name: Set up docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

